### ISSUE TITLE
Add in "function link" handler.

### ISSUE THREAD

**Issue by JWDT** [JWDT/csv_converter#1]
This will work in a similar way to the lambda handler, but instead of including the function code within the JSON, it will just reference a python function.

`{
  "New Header One": {
    "old_column": "Old Header One",
    "default": "DEFAULT FOR ONE",
    "lambda": "lambda a, b: str(a.get(b.get('old_column'))).lower()"
  },
  "New Header Two": {
    "old_column": "Old Header Two",
    "default": "DEFAULT FOR TWO",
    "funlink": "custom_python_file_or_module/custom_function"
  }
}
`

It would then split the string by the forward slash, and import it using:

https://docs.python.org/3/library/importlib.html

Finally, it would run the imported function, in a similar way to the lambda one, with the following variables:

input_line - the current INPUT line
previous_input_lines - all the previous input file lines
current_output_lines - the current output dictionary, not a copy, but the actual one, so these functions are able to view values from, and make changes to previous entries.
item - the current column item in the JSON config.

It would output both the individual item it is processing, as well as the current_output_lines, which is to be updated if there are any changes.

**Comment by nnamdiib** [comment]
If you want the imported function to be run with `previous_input_lines` and `current_output_lines`, then I think it would change the way the code is organized. For example, I think it would be easier if the JSON config is structured this way:
`{
	"original header 1": {
		"new header": "NEW HEADER 1",
		"default": "A default value",
		"lambda": ...
		"funlink": ...
	}
}`
`original header 1` is the actual header in the CSV file. It will point to a dictionary that will contain values for which new header title to give (new header), if any, a default value to use for that column, a lambda and/or a function link as proposed.

Also, if a Lambda and Funlink are specified in the config, should both be executed? I think the funlink should have a higher order of precedence.

**Comment by JWDT** [comment]
It's structured this way as the output file can contain a column with multiple source columns, for example "full name": {"lambda": "...first_name + last_name..."}

There shouldn't actually be an "old column" mentioned at all in the examples above, that's my bad, though perhaps this would work:

Go through each possible type of value in this order, and if it returns None or an exception, try the next one.

1. funlink
2. Lambda
3. Old column
4. Default

**Comment by nnamdiib** [comment]
Alright. I'm currently adding some tests for my funlinks implementation. Hopefully I'll be done tonight.
